// Generated by gencpp from file my_pack/WordCount.msg
// DO NOT EDIT!


#ifndef MY_PACK_MESSAGE_WORDCOUNT_H
#define MY_PACK_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <my_pack/WordCountRequest.h>
#include <my_pack/WordCountResponse.h>


namespace my_pack
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace my_pack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_pack::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::my_pack::WordCount&) { return value(); }
};

template<>
struct DataType< ::my_pack::WordCount > {
  static const char* value()
  {
    return "my_pack/WordCount";
  }

  static const char* value(const ::my_pack::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::my_pack::WordCountRequest> should match
// service_traits::MD5Sum< ::my_pack::WordCount >
template<>
struct MD5Sum< ::my_pack::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_pack::WordCount >::value();
  }
  static const char* value(const ::my_pack::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_pack::WordCountRequest> should match
// service_traits::DataType< ::my_pack::WordCount >
template<>
struct DataType< ::my_pack::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::my_pack::WordCount >::value();
  }
  static const char* value(const ::my_pack::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_pack::WordCountResponse> should match
// service_traits::MD5Sum< ::my_pack::WordCount >
template<>
struct MD5Sum< ::my_pack::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_pack::WordCount >::value();
  }
  static const char* value(const ::my_pack::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_pack::WordCountResponse> should match
// service_traits::DataType< ::my_pack::WordCount >
template<>
struct DataType< ::my_pack::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::my_pack::WordCount >::value();
  }
  static const char* value(const ::my_pack::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_PACK_MESSAGE_WORDCOUNT_H
